In [1]:
import numpy as np

In [2]:
s = 5
s

5

In [3]:
v = np.array([5, -2, 6])
v

array([ 5, -2,  6])

In [4]:
m = np.array([[5,12,6],[4, 14, -1]])
m

array([[ 5, 12,  6],
       [ 4, 14, -1]])

In [5]:
v.reshape(1, 3)

array([[ 5, -2,  6]])

In [6]:
v.reshape(3, 1)

array([[ 5],
       [-2],
       [ 6]])

In [8]:
m1 = np.array([[5, 12, 6], [7, 9, 0]])
m2 = np.array([[-1, 0, 2], [5, 8, 4]])

In [9]:
t = np.array([m1, m2])
t

array([[[ 5, 12,  6],
        [ 7,  9,  0]],

       [[-1,  0,  2],
        [ 5,  8,  4]]])

In [10]:
t.shape

(2, 2, 3)

In [11]:
m1+m2

array([[ 4, 12,  8],
       [12, 17,  4]])

In [12]:
m1-m2

array([[ 6, 12,  4],
       [ 2,  1, -4]])

In [13]:
v.T

array([ 5, -2,  6])

In [14]:
m1.T

array([[ 5,  7],
       [12,  9],
       [ 6,  0]])

In [15]:
m1

array([[ 5, 12,  6],
       [ 7,  9,  0]])

In [18]:
v1 = np.array([4, 2, 3])
v1

array([4, 2, 3])

In [17]:
v

array([ 5, -2,  6])

In [19]:
np.dot(v, v1)

34